### ISSUE TITLE
Feature request: mount directories containing archive files

### ISSUE THREAD

**Issue by wlritchi** [google/fuse-archive#12]
### Use case

I have a directory tree containing both a large number of bare files, and a large number of archives. I would like to mount a FUSE filesystem that gives a read-only view of this directory tree, but wherein all archives are instead exposed as directories, as if each had been separately mounted via `fuse-archive`.

For example, if I have the following tree:
```
dir/archive1.tar.gz  # contains contents1.txt and contents2.txt
dir/file1.txt
dir/inner/archive2.tar.gz  # contains contents3.txt and contents4.txt
dir/inner/file2.txt
```
and I mount it with `fuse-archive dir mnt`, I expect to see the following in the mount point:
```
mnt/archive1.tar.gz/contents1.txt
mnt/archive1.tar.gz/contents2.txt
mnt/file1.txt
mnt/inner/archive2.tar.gz/contents3.txt
mnt/inner/archive2.tar.gz/contents4.txt
mnt/inner/file2.txt
```

### Performance and limitations

I imagine that when the contents of a directory are listed, each file in the backing directory will need at least some inspection to determine whether it is an unpackable archive, and this necessarily incurs some performance penalty (which I'm willing to accept). I expect the most effective solution to this problem is for users to avoid large, flat directories.

Provided that users exercise reasonable restraint in making parallel accesses, it should be possible to mount and use a directory tree containing, say, a million archives. For example, it should be possible to run `find` on the mount point, with performance at least equal to (and ideally much better than) `find`ing all files, checking which ones are archives, sequentially mounting each archive individually, and running `find` on the resulting mount points.

Access to each of the archives should be lazy, and the initial mounting process should not require recursively scanning the entire directory tree. In particular, even if the directory tree contains a million archives, there should be no appreciable difference in performance between:
1. mounting a single archive deep in the directory tree, and then accessing a single file within it, or
2. mounting the top of a large directory tree, and then accessing a single file within a single archive deep in that tree

Recursive unpacking is not required for my use case; however, I can imagine other users may want this option.

### Considered alternatives

For a small number of archives, it might be possible to use overlayfs, unionfs, or similar with a startup script that simply enumerates archives in the backing directory and mounts them individually. However, as the number of archives increases, this solution would probably also incur linear growth in startup time, in number of processes, in number of mounts, and in memory usage.

It might also be possible for this script to use autofs mounts for each archive, allowing the `fuse-archive` processes to be created lazily. Unfortunately, this probably doesn't solve the issue with startup time nor number of mounts, and I expect that it would be quite difficult to get auto-unmounting right.

### Prior art

* [ratarmount](https://github.com/mxmlnkn/ratarmount) supports this use case, though I believe only for a subset of the archive types that fuse-archive supports.
* [rar2fs](https://hasse69.github.io/rar2fs/) supports this use case for rar files specifically.
* #5 touches on this use case, but IMHO the discussion there seemed a bit more focused on some gzip-specific questions that aren't really on-topic for this feature request (though some may come up when considering edge cases).

**Comment by mxmlnkn** [comment]
@wlritchi I didn't see it in your considered alternatives, but [ratarmount](https://github.com/mxmlnkn/ratarmount) supports such `--lazy --recursive` mounting options. It is written (by me) in Python though, I'm not sure whether that matches your intended use case.

**Comment by wlritchi** [comment]
> @wlritchi I didn't see it in your considered alternatives, but [ratarmount](https://github.com/mxmlnkn/ratarmount) supports such `--lazy --recursive` mounting options. It is written (by me) in Python though, I'm not sure whether that matches your intended use case. Try `ratarmount --recursive --lazy dir mnt; ls -la mnt`.

Nice! That looks like it'll work for me. Added it to the Prior Art section.

I'll leave this feature request open in case there's still interest in fuse-archive supporting the same.

**Comment by mxmlnkn** [comment]
> I believe only for a subset of the archive types that fuse-archive supports.

That is true for now. There is an open pull request for libarchive support. I hope to get that polished and merged soon. Then, it should support the same amount of compression types as fuse-archive with hopefully similar performance. The real performance benefits over other solutions will then be the [seekable parallel bzip2](https://github.com/mxmlnkn/indexed_bzip2) backend and the hopefully the very soon-to-be-integrated seekable parallelized gzip decoder, [pragzip](https://github.com/mxmlnkn/pragzip).

**Comment by fdegros** [comment]
Thanks for the request.

We aren't planning to implement this feature in `fuse-archive` for the time being.
