### ISSUE TITLE
Nonstandard-C++ in src/main.cc

### ISSUE THREAD

**Issue by jpedrick** [google/fuse-archive#15]
my_operations is initialized using non-standard C++ syntax. Why not just initialize with a function instead?

```
struct fuse_operations init_my_operations(){
     struct fuse_operations opers = {};
     opers.getattr = my_getattr;
     opers.readlink = my_readlink;
     opers.open = my_open;
     opers.read = my_read;
     opers.release = my_release;
     opers.readdir = my_readdir;
     opers.init = my_init;
     opers.destroy = my_destroy;
  
     return opers;
 }
  
static struct fuse_operations my_operations = init_my_operations();
```

**Comment by fdegros** [comment]
[Designated initializers](https://en.cppreference.com/w/cpp/language/aggregate_initialization#Designated_initializers) are part of the C++20 standard. They have been implemented or back-ported by most C++ compilers, even when compiling with previous versions of the C++ standard.
