### ISSUE TITLE
[feature request] Upstream to libarchive an example containing building FS context and open/read/seek impls (basically untie fuse-archive from FUSE headers)

### ISSUE THREAD

**Issue by vadimkantorov** [google/fuse-archive#21]
This would be very beneficial for all other users trying to achieve some sort of virtual FS based on libarchive and improve visibility of the implementation ideas in this project. Untying from FUSE headers should be relatively simple.

The folders for contrib examples:
- https://github.com/libarchive/libarchive/blob/master/examples/
- https://github.com/libarchive/libarchive/blob/master/contrib/

**Comment by vadimkantorov** [comment]
It seems that the approach of fuse-archive to random seeking is quite ingenious (as for now libarchive does not support random seeks) and likely would be welcome as an example in upstream, as it's a quite popular request

**Comment by fdegros** [comment]
I'm not sure what this feature request is exactly about.

What would a `fuse-archive` user be able to do once this feature request is implemented?

**Comment by fdegros** [comment]
So, if I understand correctly, this is a feature request for the `libarchive` library, and not for the `fuse-archive` program. If my understanding is correct, I invite you to file a feature request with the `libarchive` library [here](https://github.com/libarchive/libarchive/issues).

**Comment by vadimkantorov** [comment]
This was a mere idea proposal for making the solution to random-seeking in libarchive developed in fuse-archive visible to a wider libarchive user base. And obviously, the fuse-archive's developers are placed the best for this type of refactoring / splitting the core mechanism out of FUSE interaction.

But of course if this idea is not something that interests fuse-archive's authors, it can be done by someone else, for both projects are open-source.
