### ISSUE TITLE
Feature request--7zip support

### ISSUE THREAD

**Issue by drkmc** [google/fuse-archive#22]
It would be handy to have 7-zip support, esp. for dealing with dual boot or thumb drives which go between Windows, Linux, and macOS systems.  While Windows will probably screw up file permissions, in most cases where this would be used (an individual or team's documents) that isn't a huge deal.  

The big advantage is the native support for AES encryption and how robust the Windows 7-zip program is (tar.7z is not a problem).  

While 7-zip can deal with tgz, tar.xz, etc. just fine, having the built-in AES support makes life easier for Windows users (I don't currently use Windows often enough, but I don't recall any simple way to decrypt a tar ball or compressed tar ball or directory of files before being sucked up into tar.)

I know you have a lot to do, but I think this would be a cool trick and make USB thumb drives less of a security nightmare.

It also would be a great solution for Dropbox users--not sure how well it would work with the virtual drive, however.  If you cache the files in the archive and update any changes into the backing archive then I would imagine you just solved a huge problem for a lot of people with the added benefit of a local cache of mounted files, plus encryption, plus pretty decent compression--esp. if your cache is in RAM, but that might be a bit dicey if it is a big archive on a small system!

**Comment by fdegros** [comment]
I'm not sure what this feature request is exactly about.

`fuse-archive` already supports and mounts `7Z` archives. However, it does not support encrypted `7Z` archives, since the underlying `libarchive` library does not support them. See this [`libarchive` feature request](https://github.com/libarchive/libarchive/issues/878).
