### ISSUE TITLE
Cannot Mount Archive Generated From 7-Zip-ZSTD

### ISSUE THREAD

**Issue by cheznewa** [google/fuse-archive#4]
Hi I Can't Mount Archive Which Generated From [7-ZIP-ZSTD](https://github.com/mcmilk/7-Zip-zstd)
A Error Show For :::::
```
sick@sick-virtualbox:~$ fuse-archive sharedvm/test_compress_zstd.7z $(mktemp -d)
fuse-archive: libarchive error for sharedvm/test_compress_zstd.7z: Unknown codec ID: 4f71101
sick@sick-virtualbox:~$ fuse-archive sharedvm/test_compress_brotli.7z $(mktemp -d)
fuse-archive: libarchive error for sharedvm/test_compress_brotli.7z: Unknown codec ID: 4f71102
sick@sick-virtualbox:~$ fuse-archive sharedvm/test_compress_lz4.7z $(mktemp -d)
fuse-archive: libarchive error for sharedvm/test_compress_lz4.7z: Unknown codec ID: 4f71104
```
So This Archive Test Contain A [Ipsum From LaTeX](https://distrib-coffee.ipsl.jussieu.fr/pub/mirrors/ctan/macros/latex/contrib/lipsum/lipsum-la.txt) And A Image Generated From ImageMagick.

[test_compress_test.zip](https://github.com/google/fuse-archive/files/7912324/test_compress_test.zip)

Newa Our Master.

**Comment by nigeltao** [comment]
Yeah, as jloqfjgk said, it's a https://github.com/libarchive/libarchive bug. Any fix would involve changing libarchive code, not fuse-archive code.

**Comment by nigeltao** [comment]
I filed https://github.com/libarchive/libarchive/issues/1656

**Comment by fdegros** [comment]
I confirm that a Zstandard-compressed 7Z file can now be mounted by `fuse-archive`.

```
$ fuse-archive test_compress_zstd.7z mnt
fuse-archive: Created mount point 'mnt'

$ tree mnt
mnt
└── test_compress
    ├── image.ff
    └── lipsum-la.txt

2 directories, 2 files
```

However, Brotli and LZ4 are not supported in 7Z.

```
$ fuse-archive test_compress_brotli.7z mnt
fuse-archive: Unknown codec ID: 4f71102

$ fuse-archive test_compress_lz4.7z mnt
fuse-archive: Unknown codec ID: 4f71104
```
