### ISSUE TITLE
Support for indexed tar.xz file from pixz tool

### ISSUE THREAD

**Issue by 0bi-w6n-K3nobi** [google/fuse-archive#8]
I already tested several fuse tool, including infamous `archivemount`, for compressed files.
I have a lot of log file into `7z`format.
At last, I did try the good one [pixz](https://github.com/vasi/pixz) and [lzofs](https://github.com/vasi/lzopfs) fuse tool  counterparty.
It's a great, but did not access `tar` in transparent way.

For solid compressed `7z` file, I know that `fuse-archive` will be indexing before that mount it, and I need wait for that.
But, for `pixz` `tar` file it's not necessary because that already had internal index.

So, Is it possible implement to use `pixz` internal index for mount?

Note:
The code for indexing and access it can founded at [common.c](https://github.com/vasi/pixz/blob/master/src/common.c) and [write.c](https://github.com/vasi/pixz/blob/master/src/write.c) files at GitHub.
The functions are called `*_file_index_*`.

**Comment by fdegros** [comment]
Since `fuse-archive` is built on top of `libarchive`, this feature request might be a feature request for `libarchive`.

**Comment by fdegros** [comment]
By default, `fuse-archive` now works in fully cached mode. See [documentation](https://github.com/google/fuse-archive/blob/main/README.md#caching). I don't think there is a need to use a third-party tool in order to scan and index a `tar.xz` archive.
