### ISSUE TITLE
C implementation

### ISSUE THREAD

**Issue by asuka-mio** [google/fuse-archive#9]
Is there any possibility to provide a c implementation?
Both libarchive and libfuse have c implementation, maybe this not such friendly for intergated usage.

**Comment by 0bi-w6n-K3nobi** [comment]
Hio @asuka-mio 

It is possible mix C++ and C code. A good documentation example site is [here](https://isocpp.org/wiki/faq/mixing-c-and-cpp)!
You need only create one source file with `wrapper functions` that you need, and compile all together for build one library.

Maybe be possible with create a simple header `.h`, defining one macro like `IS_LIBRARY`.
So it is `true` at library building/linking time, and `false` for use into your program.

I hope that could helped You.

**Comment by asuka-mio** [comment]
> Hio @asuka-mio
> 
> It is possible mix C++ and C code. A good documentation example site is [here](https://isocpp.org/wiki/faq/mixing-c-and-cpp)! You need only create one source file with `wrapper functions` that you need, and compile all together for build one library.
> 
> Maybe be possible with create a simple header `.h`, defining one macro like `IS_LIBRARY`. So it is `true` at library building/linking time, and `false` for use into your program.
> 
> I hope that could helped You.

Thanks, but that's not i really confused about, the real reason is that i try to avoid the introduction of libc++, which will make size bloat a bit in some degree.

**Comment by fdegros** [comment]
Thanks for the request.

We are not planning to rewrite `fuse-archive` in C. It is currently written in C++14.
On my workstation, the stripped `fuse-archive` program just "weighs" 80 KB.

```
$ make
mkdir -p out
g++  -I/usr/include/fuse -D_FILE_OFFSET_BITS=64  src/main.cc  -larchive -lfuse -pthread  -o out/fuse-archive

$ ls -lh out/fuse-archive 
-rwxr-xr-x 1 fdegros primarygroup 150K Aug  4 11:25 out/fuse-archive

$ strip out/fuse-archive 

$ ls -lh out/fuse-archive 
-rwxr-xr-x 1 fdegros primarygroup 80K Aug  4 11:25 out/fuse-archive

$ file out/fuse-archive 
out/fuse-archive: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=aeceb679a64e2eac695571af529b50685be8bab4, for GNU/Linux 3.2.0, stripped

```
